[server]
address = "127.0.0.1:8000"

[mysql]
dsn = "popsenzawa_echo:popsenzawa_echo@tcp(127.0.0.1:3306)/popsenzawa_echo"

[geolite2]
database_path = "/tmp/ip_geo.mmdb"

[redis]
network = "tcp"
address = "127.0.0.1:6379"
database = 0

[pop_rules]
jwt_secret = "popsenzawa_echo"
recaptcha_secret = "popsenzawa_echo"
